name: Deploy to AWS
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: instantiate node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: install dependencies
        run: npm ci
      - name: run prettier
        run: npm run prettier:check
      - name: run eslint
        run: npm run eslint:check
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: instantiate node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: install dependencies
        run: npm ci
      - name: result
        run: echo 'Success'