name: Deploy to AWS
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Instantiate node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:check
      - name: Run eslint
        run: npm run eslint:check
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub repo
        uses: actions/checkout@v3
      - name: Instantiate node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install portfolio dependencies
        run: npm ci
      - name: Generate static build files
        run: npm run build
      - name: Install aws-cdk dependencies
        working-directory: ./aws-cdk
        run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Synthesise aws stack
        working-directory: ./aws-cdk
        run: npm run cdk synth
      - name: Deploy to AWS
        working-directory: ./aws-cdk
        run: npm run cdk deploy