name: Run test suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Instantiate node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:check
      - name: Run eslint
        run: npm run eslint:check